name: flutter_food_recog
description: "A Flutter application for food recognition using TensorFlow Lite."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  camera: ^0.11.1
  cupertino_icons: ^1.0.8
  device_info_plus: ^11.4.0
  envied: ^1.1.1
  flutter:
    sdk: flutter
  flutter_isolate: ^2.0.5
  google_generative_ai: ^0.4.7
  google_generative_language_api: ^0.2.1
  http: ^1.2.0
  image: ^4.5.2
  image_cropper: ^9.1.0
  image_picker: ^1.0.7
  path: ^1.8.3
  path_provider: ^2.1.2
  permission_handler: ^12.0.0+1
  provider: ^6.1.2
  tflite_flutter: ^0.11.0

dev_dependencies:
  build_runner: ^2.4.8
  envied_generator: ^1.1.1
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/labels.txt