import 'dart:convert';
import 'dart:io';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';
import 'package:google_generative_ai/google_generative_ai.dart';
import 'package:http/http.dart' as http;
import 'package:image/image.dart' as img;
import 'package:path/path.dart' as path;
import 'package:path_provider/path_provider.dart';
import 'package:tflite_flutter/tflite_flutter.dart';

import '../utils/env.dart';

class FoodRecognitionProvider extends ChangeNotifier {
  Interpreter? _interpreter;
  bool _isModelLoaded = false;
  bool _isProcessing = false;
  Map<String, dynamic>? _lastPrediction;
  Map<String, dynamic>? _lastMealData;
  Map<String, dynamic>? _lastNutritionalData;

  bool _isIdentifyingFood = false;
  bool _isFetchingMealData = false;
  bool _isFetchingNutritionalData = false;

  bool get isModelLoaded => _isModelLoaded;
  bool get isProcessing => _isProcessing;
  Map<String, dynamic>? get lastPrediction => _lastPrediction;
  Map<String, dynamic>? get lastMealData => _lastMealData;
  Map<String, dynamic>? get lastNutritionalData => _lastNutritionalData;

  bool get isIdentifyingFood => _isIdentifyingFood;
  bool get isFetchingMealData => _isFetchingMealData;
  bool get isFetchingNutritionalData => _isFetchingNutritionalData;

  FoodRecognitionProvider() {
    loadModel();
  }

  Future<void> loadModel() async {
    if (_isModelLoaded) return;
    try {
      _isProcessing = true;
      notifyListeners();

      final modelFile = await _getModelFile('assets/aiy.tflite', 'aiy.tflite');
      final options = InterpreterOptions();
      _interpreter = Interpreter.fromFile(modelFile, options: options);

      _isModelLoaded = true;
      debugPrint("LOG: Model loaded successfully. Labels are embedded.");
    } catch (e) {
      debugPrint('LOG: Error loading model: $e');
      _isModelLoaded = false;
    } finally {
      _isProcessing = false;
      notifyListeners();
    }
  }

  Future<File> _getModelFile(String assetPath, String fileName) async {
    final appDir = await getApplicationDocumentsDirectory();
    final modelPath = path.join(appDir.path, fileName);
    final modelFile = File(modelPath);

    if (!await modelFile.exists()) {
      final modelData = await rootBundle.load(assetPath);
      await modelFile.writeAsBytes(modelData.buffer.asUint8List());
    }
    return modelFile;
  }

  void clearLastData() {
    _lastPrediction = null;
    _lastMealData = null;
    _lastNutritionalData = null;
    _isIdentifyingFood = false;
    _isFetchingMealData = false;
    _isFetchingNutritionalData = false;
    _isProcessing = false;
    notifyListeners();
  }

   Future<void> processImageAndFetchDetails(String imagePath) async {
    try {
      _isProcessing = true;
      _isIdentifyingFood = true;
      _lastMealData = null;
      _lastNutritionalData = null;
      _lastPrediction = null;
      notifyListeners();
      debugPrint("==================================================");
      debugPrint("LOG: Starting food recognition process...");

      // 1. Dapatkan nama dari TFLite
      final foodName = await _getFoodNameFromImageWithTFLite(imagePath);
      _isIdentifyingFood = false;

      if (foodName == null || foodName == "Unknown Food") {
        _lastPrediction ??= {
          'label': 'Unknown Food',
          'confidence': _lastPrediction?['confidence'] ?? 0.0,
        };
        debugPrint(
          "LOG: Food not recognized or confidence too low. Ending process.",
        );
        _isProcessing = false;
        notifyListeners();
        debugPrint("==================================================");
        return;
      }
      notifyListeners();

      // 2. Ambil data meal menggunakan nama langsung dari TFLite
      _isFetchingMealData = true;
      notifyListeners();
      await _fetchMealData(foodName);
      _isFetchingMealData = false;
      notifyListeners();

      // 3. Ambil data nutrisi. Gunakan nama dari TheMealDB jika ada, jika tidak, gunakan nama dari TFLite.
      final finalFoodNameForNutrition =
          _lastMealData?['strMeal'] as String? ?? foodName;
      _isFetchingNutritionalData = true;
      notifyListeners();
      await _fetchNutritionalData(finalFoodNameForNutrition);
      _isFetchingNutritionalData = false;
      notifyListeners();
    } catch (e) {
      debugPrint('LOG: ERROR in prediction process: $e');
      _lastPrediction = {
        'label': 'Error',
        'confidence': 0.0,
        'error': e.toString(),
      };
    } finally {
      _isIdentifyingFood = false;
      _isFetchingMealData = false;
      _isFetchingNutritionalData = false;
      _isProcessing = false;
      notifyListeners();
      debugPrint("LOG: Food recognition process finished.");
      debugPrint("==================================================");
    }
  }
   Future<void> fetchDetailsForCorrectedName(String correctedName) async {
    // Set state loading
    _isFetchingMealData = true;
    _isFetchingNutritionalData = true;
    _lastMealData = null; // Kosongkan data lama
    _lastNutritionalData = null;
    notifyListeners();

    // Perbarui prediksi dengan nama yang benar dari pengguna
    if (_lastPrediction != null) {
      _lastPrediction!['label'] = correctedName;
    } else {
      _lastPrediction = {
        'label': correctedName,
        'confidence': 1.0,
      }; // Anggap 100% karena dari user
    }

    debugPrint(
      "LOG: User corrected name to '$correctedName'. Fetching new details...",
    );

    // Ambil data meal
    await _fetchMealData(correctedName);
    _isFetchingMealData = false;
    notifyListeners();

    // Ambil data nutrisi
    await _fetchNutritionalData(correctedName);
    _isFetchingNutritionalData = false;
    notifyListeners();

    debugPrint("LOG: Process finished for corrected name '$correctedName'.");
  }

  Future<String?> _getFoodNameFromImageWithTFLite(String imagePath) async {
    if (!_isModelLoaded || _interpreter == null) {
      debugPrint("LOG: Model not loaded, attempting to load now...");
      await loadModel();
      if (!_isModelLoaded) return "Error: Model failed to load";
    }

    final imageData = File(imagePath).readAsBytesSync();
    final image = img.decodeImage(imageData)!;
    final resizedImage = img.copyResize(image, width: 224, height: 224);

    final inputBytes = resizedImage.getBytes(order: img.ChannelOrder.rgb);
    final input = inputBytes.reshape([1, 224, 224, 3]);

    final outputShape = _interpreter!.getOutputTensor(0).shape;
    final output = List.generate(
      outputShape.reduce((a, b) => a * b),
      (_) => 0,
    ).reshape(outputShape);

    _interpreter!.run(input, output);

    final result = output[0] as List<int>;
    double maxConfidence = 0.0;
    int maxIndex = -1;

    for (int i = 0; i < result.length; i++) {
      final confidence = result[i] / 255.0;
      if (confidence > maxConfidence) {
        maxConfidence = confidence;
        maxIndex = i;
      }
    }

    if (maxIndex != -1 &&
        maxIndex < _foodLabels.length &&
        maxConfidence > 0.5) {
      final foodName = _foodLabels[maxIndex].replaceAll('_', ' ');
      _lastPrediction = {'label': foodName, 'confidence': maxConfidence};
      debugPrint(
        "LOG: TFLite recognized '$foodName' with confidence ${(maxConfidence * 100).toStringAsFixed(1)}%",
      );
      return foodName;
    } else {
      _lastPrediction = {'label': 'Unknown Food', 'confidence': maxConfidence};
      debugPrint(
        "LOG: TFLite could not recognize food with high confidence. Max confidence: ${(maxConfidence * 100).toStringAsFixed(1)}%",
      );
      return "Unknown Food";
    }
  }

  Future<void> _fetchMealData(String foodLabel) async {
    // **PERUBAHAN: Ganti spasi dengan underscore untuk URL API**
    final apiFoodLabel = foodLabel.replaceAll(' ', '_');
    debugPrint(
      "LOG: Fetching meal data for: '$foodLabel' (using URL parameter: '$apiFoodLabel')",
    );

    try {
      final uri = Uri.parse(
        'https://www.themealdb.com/api/json/v1/1/search.php?s=$apiFoodLabel',
      );
      debugPrint("LOG: TheMealDB API URL: $uri");

      final response = await http.get(uri);

      if (response.statusCode == 200) {
        final data = json.decode(response.body);
        if (data['meals'] != null && data['meals'].isNotEmpty) {
          _lastMealData = data['meals'][0];
          debugPrint(
            "LOG: SUCCESS - Meal data found for '$foodLabel'. Recipe: ${_lastMealData?['strMeal']}",
          );
        } else {
          _lastMealData = null;
          debugPrint(
            "LOG: FAILED - Meal data NOT found for '$foodLabel' in TheMealDB.",
          );
        }
      } else {
        _lastMealData = null;
        debugPrint(
          "LOG: FAILED - TheMealDB API returned status code ${response.statusCode}",
        );
      }
    } catch (e) {
      debugPrint('LOG: ERROR fetching meal data: $e');
      _lastMealData = null;
    }
  }

  Future<void> _fetchNutritionalData(String foodName) async {
    debugPrint("LOG: Fetching nutritional data for: '$foodName' using Gemini.");
    try {
      final model = GenerativeModel(
        model: 'gemini-2.0-flash',
        apiKey: Env.geminiApiKey,
      );
      final prompt =
          'Provide typical nutritional data (calories, carbohydrates, protein, fat, fiber) for a standard serving of $foodName. Please respond in a clean JSON format. Each value should be a single, static string representing a typical value, not a range. For example: {"calories": "250 kcal", "carbohydrates": "30g", "protein": "10g", "fat": "12g", "fiber": "3g"}.';

      final content = [Content.text(prompt)];
      final response = await model.generateContent(content);

      if (response.text != null) {
        String jsonString = response.text!
            .replaceAll('```json', '')
            .replaceAll('```', '')
            .trim();
        _lastNutritionalData = json.decode(jsonString);
        debugPrint("LOG: Nutritional data from Gemini received successfully.");
      } else {
        debugPrint("LOG: Gemini did not return text for nutritional data.");
      }
    } catch (e) {
      debugPrint('LOG: ERROR fetching nutritional data from Gemini: $e');
    }
  }

  @override
  void dispose() {
    _interpreter?.close();
    super.dispose();
  }

  static const List<String> _foodLabels = [
    "background",
    "ajo_blanco",
    "albondigas",
    "aloo_gobi",
    "ancho_chile_relleno",
    "antipasto_salad",
    "apple_fritter",
    "apple_pie",
    "apple_strudel",
    "arroces",
    "arugula_salad",
    "asparagus",
    "asparagus_risotto",
    "asparagus_salad",
    "assiette_de_crudites",
    "avgolemono",
    "avocado_toast",
    "baba_ghanoush",
    "baby_back_ribs",
    "baby_carrots",
    "bacon",
    "bacon_and_eggs",
    "bacon_cheeseburger",
    "bacon_lettuce_tomato_sandwich",
    "bagel",
    "baguette",
    "baharat",
    "baklava",
    "baked_alaska",
    "baked_potato",
    "baked_ziti",
    "bakewell_tart",
    "balsamic_vinaigrette",
    "bangers_and_mash",
    "banh_mi",
    "bannock",
    "barbecued_spareribs",
    "barbecued_wing",
    "bartlett_pear",
    "basil",
    "basil_pesto",
    "bass",
    "battenberg_cake",
    "bbq_chicken_pizza",
    "bbq_pulled_pork_sandwich",
    "beans",
    "bearnaise_sauce",
    "beatas",
    "beaver_tail",
    "beef_and_broccoli",
    "beef_bourguignon",
    "beef_carpaccio",
    "beef_jerky",
    "beef_samosa",
    "beef_sate",
    "beef_stew",
    "beef_wellington",
    "beer",
    "beer_battered_fish_and_chips",
    "beet_salad",
    "beignet",
    "bell_pepper",
    "berries",
    "berry",
    "bibimbap",
    "bigos",
    "biryani",
    "biscuits_and_gravy",
    "biscotti",
    "bison_burger",
    "bisque",
    "bistec_encebollado",
    "black_bean_burger",
    "black_bean_soup",
    "black_eyed_pea",
    "black_forest_cake",
    "black_olive",
    "black_pudding",
    "black_rice",
    "black_truffle",
    "blini",
    "blintz",
    "blood_orange",
    "bloody_mary",
    "blueberry",
    "blueberry_cobbler",
    "blueberry_muffin",
    "blueberry_pancakes",
    "blueberry_pie",
    "blueberry_scone",
    "blt",
    "boar",
    "boeuf_bourguignon",
    "bok_choy",
    "bolo_de_mel",
    "bolognese",
    "bombay_duck",
    "bonbon",
    "borscht",
    "boston_cream_pie",
    "bouillabaisse",
    "bourbon_chicken",
    "bresaola",
    "bread",
    "bread_and_butter_pudding",
    "bread_pudding",
    "breaded_shrimp",
    "breakfast_burrito",
    "brie",
    "brioche",
    "brisket",
    "broccoli",
    "broccoli_cheddar_soup",
    "brown_rice",
    "brownie",
    "brunoise",
    "brussels_sprouts",
    "bruschetta",
    "bubble_and_squeak",
    "bubble_tea",
    "buckwheat",
    "buddha_bowl",
    "buffalo_wing",
    "bulgogi",
    "burrito",
    "butter",
    "butter_chicken",
    "buttermilk_pancakes",
    "butternut_squash",
    "butternut_squash_risotto",
    "butternut_squash_soup",
    "cabbage",
    "cabbage_roll",
    "cabbage_soup",
    "caesar_salad",
    "cajun_shrimp",
    "calamari",
    "california_roll",
    "calzone",
    "canary_melon",
    "cannele",
    "cannelloni",
    "cannoli",
    "cantaloupe",
    "caponata",
    "cappuccino",
    "caprese_salad",
    "caramel_apple",
    "caramel_corn",
    "caramel_sauce",
    "caramel_slice",
    "carbonara",
    "carne_asada",
    "carnitas",
    "carrot",
    "carrot_cake",
    "cashew_chicken",
    "cassoulet",
    "cauliflower",
    "cavatelli",
    "caviar",
    "cevapcici",
    "ceviche",
    "chai",
    "chai_latte",
    "challah",
    "chamomile_tea",
    "channa_masala",
    "chantilly_cake",
    "chapati",
    "charlotte",
    "chateaubriand",
    "chayote",
    "cheddar_cheese",
    "cheerios",
    "cheese",
    "cheese_and_crackers",
    "cheese_ball",
    "cheese_curds",
    "cheese_fries",
    "cheese_plate",
    "cheesecake",
    "cheesesteak",
    "cherimoya",
    "cherry",
    "cherry_pie",
    "chervil",
    "chestnut",
    "chicago_style_pizza",
    "chicken",
    "chicken_and_dumplings",
    "chicken_and_waffles",
    "chicken_breast",
    "chicken_caesar_salad",
    "chicken_curry",
    "chicken_fajita",
    "chicken_fried_steak",
    "chicken_katsu",
    "chicken_korma",
    "chicken_liver_pate",
    "chicken_marengo",
    "chicken_marsala",
    "chicken_noodle_soup",
    "chicken_nuggets",
    "chicken_pesto_pasta",
    "chicken_piccata",
    "chicken_pot_pie",
    "chicken_quesadilla",
    "chicken_salad",
    "chicken_salad_sandwich",
    "chicken_satay",
    "chicken_schnitzel",
    "chicken_soup",
    "chicken_stew",
    "chicken_stir_fry",
    "chicken_tenders",
    "chicken_teriyaki",
    "chicken_tikka",
    "chicken_tikka_masala",
    "chicken_tortilla_soup",
    "chicken_vinga",
    "chicken_wings",
    "chickpea",
    "chickpea_curry",
    "chickpea_salad",
    "chilaquiles",
    "chile_con_carne",
    "chile_relleno",
    "chiles_en_nogada",
    "chili",
    "chili_cheese_dog",
    "chili_cheese_fries",
    "chili_con_carne",
    "chili_dog",
    "chili_powder",
    "chimichanga",
    "chimichurri",
    "chinese_cabbage",
    "chinese_hot_pot",
    "chinese_steamed_buns",
    "churro",
    "cioppino",
    "chip",
    "chipotle_pepper",
    "chive",
    "chlodnik",
    "chocolate",
    "chocolate_bar",
    "chocolate_biscotti",
    "chocolate_brownie",
    "chocolate_cake",
    "chocolate_chip_cookie",
    "chocolate_chip_cookie_dough_ice_cream",
    "chocolate_chip_pancakes",
    "chocolate_croissant",
    "chocolate_fondue",
    "chocolate_ice_cream",
    "chocolate_lava_cake",
    "chocolate_milk",
    "chocolate_mousse",
    "chocolate_pudding",
    "chocolate_souffle",
    "chocolate_truffle",
    "chorizo",
    "christmas_cake",
    "christmas_pudding",
    "chutney",
    "ciabatta",
    "cilantro",
    "cinnamon",
    "cinnamon_roll",
    "clam",
    "clam_chowder",
    "clamato",
    "clams_casino",
    "clementine",
    "club_sandwich",
    "cob_salad",
    "cobb_salad",
    "cock_a_leekie_soup",
    "cockle",
    "cocktail",
    "cocktail_sauce",
    "cocoa_bean",
    "coconut",
    "coconut_cake",
    "coconut_cream_pie",
    "coconut_macaroon",
    "coconut_milk",
    "coconut_shrimp",
    "cod",
    "coffee",
    "coffee_cake",
    "cognac",
    "coleslaw",
    "collard_greens",
    "comte_cheese",
    "conch",
    "conch_fritters",
    "concord_grape",
    "condensed_milk",
    "congee",
    "conpoy",
    "consomme",
    "cookie",
    "coq_au_vin",
    "coquilles_saint_jacques",
    "coriander",
    "corn",
    "corn_and_black_bean_salsa",
    "corn_chowder",
    "corn_dog",
    "corn_fritter",
    "corn_flakes",
    "corn_pudding",
    "cornbread",
    "cornbread_stuffing",
    "corned_beef",
    "corned_beef_and_cabbage",
    "corned_beef_hash",
    "cornish_hen",
    "cornish_pasty",
    "cottage_cheese",
    "cottage_pie",
    "cotton_candy",
    "couscous",
    "cow",
    "crab",
    "crab_cake",
    "crab_rangoon",
    "cracked_wheat_bread",
    "cranachan",
    "cranberry",
    "cranberry_sauce",
    "crawfish_boil",
    "cream",
    "cream_cheese",
    "cream_cheese_frosting",
    "cream_of_broccoli_soup",
    "cream_of_mushroom_soup",
    "cream_of_tomato_soup",
    "creamed_corn",
    "creamed_spinach",
    "creme_anglaise",
    "creme_brulee",
    "creme_caramel",
    "creme_fraiche",
    "crepe",
    "crepe_suzette",
    "cress",
    "croissant",
    "croque_madame",
    "croque_monsieur",
    "crostini",
    "crouton",
    "crudites",
    "cruller",
    "crumble",
    "crumpet",
    "crushed_red_pepper",
    "crustacean",
    "cucumber",
    "cucumber_salad",
    "cucumber_sandwich",
    "cullen_skink",
    "cupcake",
    "currant",
    "curry",
    "curry_chicken",
    "currywurst",
    "custard",
    "custard_tart",
    "cuttlefish",
    "daal",
    "daikon",
    "dal",
    "dal_makhani",
    "dandelion_green",
    "danish_pastry",
    "dark_chocolate",
    "dashi",
    "date",
    "daube",
    "deep_dish_pizza",
    "deer",
    "deviled_egg",
    "devils_food_cake",
    "dhansak",
    "dill",
    "dim_sum",
    "dionaea_muscipula",
    "dirt_cake",
    "dirty_rice",
    "dobos_torte",
    "dohl",
    "dolma",
    "doner_kebab",
    "donut",
    "dorayaki",
    "dosa",
    "doughnut",
    "dover_sole",
    "dragon_fruit",
    "dream_whip",
    "dreamsicle",
    "dried_apricot",
    "dried_cranberry",
    "dried_fig",
    "dried_fruit",
    "drop_biscuit",
    "duck",
    "duck_a_l_orange",
    "duck_confit",
    "duff",
    "dulce_de_leche",
    "dumpling",
    "dundee_cake",
    "dungeness_crab",
    "durian",
    "eccles_cake",
    "eclair",
    "edamame",
    "eel",
    "egg",
    "egg_benedict",
    "egg_drop_soup",
    "egg_fried_rice",
    "egg_roll",
    "egg_salad",
    "egg_salad_sandwich",
    "eggnog",
    "eggplant",
    "eggplant_parmesan",
    "eggs_benedict",
    "embutido",
    "empanada",
    "enchilada",
    "endive",
    "english_muffin",
    "epazote",
    "escabeche",
    "escargot",
    "escarole",
    "espresso",
    "eton_mess",
    "eclair",
    "farfalle",
    "fasolada",
    "fatayer",
    "fattoush",
    "fava_bean",
    "feijoa",
    "fennel",
    "fennel_salad",
    "fenugreek",
    "feta",
    "feta_salad",
    "fettuccine",
    "fettuccine_alfredo",
    "fideua",
    "fig",
    "filbert",
    "filet_mignon",
    "filo",
    "financier",
    "finnish_pulla",
    "fish",
    "fish_and_chips",
    "fish_cake",
    "fish_chowder",
    "fish_fry",
    "fish_taco",
    "flan",
    "flank_steak",
    "flapjack",
    "flatbread",
    "flatfish",
    "flauta",
    "flemish_stew",
    "florentine_biscuit",
    "flounder",
    "focaccia",
    "foie_gras",
    "fondant",
    "fondue",
    "fool",
    "forastero",
    "fortune_cookie",
    "frangipane",
    "frankfurter",
    "freekeh",
    "french_bread",
    "french_dip",
    "french_fries",
    "french_onion_soup",
    "french_toast",
    "frisee",
    "fritter",
    "focaccia",
    "frog_leg",
    "fromage_blanc",
    "frosting",
    "frozen_yogurt",
    "fruit",
    "fruit_cake",
    "fruit_cocktail",
    "fruit_compote",
    "fruit_cup",
    "fruit_salad",
    "fruit_tart",
    "frumenty",
    "fudge",
    "fudge_sundae",
    "fugu",
    "ful_medames",
    "funnel_cake",
    "fusilli",
    "galantine",
    "ganache",
    "garam_masala",
    "garbanzo_bean",
    "garlic",
    "garlic_bread",
    "garlic_shrimp",
    "gazpacho",
    "gefilte_fish",
    "gelatin",
    "gelato",
    "genoise",
    "geoduck",
    "german_chocolate_cake",
    "ghee",
    "goulash",
    "giblet",
    "gigot_d_agneau_pleureur",
    "gin",
    "ginger",
    "ginger_ale",
    "ginger_beer",
    "ginger_biscuit",
    "ginger_snaps",
    "gingersnap",
    "gnocchi",
    "goat",
    "goat_cheese",
    "goat_cheese_salad",
    "gobo",
    "goji_berry",
    "golden_delicious_apple",
    "golden_kiwi",
    "golden_raisin",
    "goose",
    "gooseberry",
    "gordita",
    "gorgonzola",
    "gouda",
    "goulash",
    "graham_cracker",
    "grain",
    "granary_bread",
    "granita",
    "granola",
    "grape",
    "grape_jelly",
    "grape_leaves",
    "grape_soda",
    "grapefruit",
    "grappa",
    "gravlax",
    "gravy",
    "greek_pizza",
    "greek_salad",
    "greek_yogurt",
    "green_bean",
    "green_bean_casserole",
    "green_curry",
    "green_goddess_dressing",
    "green_lentil",
    "green_olive",
    "green_onion",
    "green_papaya_salad",
    "green_pepper",
    "green_tea",
    "greens",
    "gremolata",
    "griddle_cake",
    "grilled_cheese_sandwich",
    "grilled_chicken_sandwich",
    "grilled_salmon",
    "grissini",
    "grits",
    "groselle",
    "ground_beef",
    "ground_cherry",
    "ground_lamb",
    "ground_pork",
    "ground_turkey",
    "grouper",
    "gruyere",
    "guacamole",
    "guava",
    "gumbo",
    "gyoza",
    "gyro",
    "habanero_pepper",
    "haddock",
    "haggis",
    "halibut",
    "halloumi",
    "ham",
    "ham_and_cheese_sandwich",
    "ham_hock",
    "ham_salad",
    "hamburger",
    "hamburger_bun",
    "hard_boiled_egg",
    "haricot_vert",
    "harissa",
    "hash_browns",
    "hawaiian_pizza",
    "hazelnut",
    "head_cheese",
    "heard_island_and_mcdonald_islands",
    "hearts_of_palm",
    "heavy_cream",
    "herbs",
    "herring",
    "hoagie_roll",
    "hoisin_sauce",
    "hollandaise_sauce",
    "hominy",
    "honey",
    "honey_mustard",
    "honeydew_melon",
    "horchata",
    "hors_d_oeuvre",
    "horseradish",
    "hot_and_sour_soup",
    "hot_brown",
    "hot_chocolate",
    "hot_cross_bun",
    "hot_dog",
    "hot_dog_bun",
    "hot_fudge_sundae",
    "hot_pot",
    "hot_toddy",
    "hot_wing",
    "huckleberry",
    "huevos_rancheros",
    "hummus",
    "hushpuppy",
    "ice_cream",
    "ice_cream_cake",
    "ice_cream_cone",
    "ice_cream_soda",
    "ice_pop",
    "iced_coffee",
    "iced_tea",
    "icing",
    "idli",
    "indian_pea",
    "indian_pudding",
    "indian_relish",
    "individual_tart",
    "injera",
    "instant_noodle",
    "irish_coffee",
    "irish_stew",
    "israeli_couscous",
    "italian_bread",
    "italian_sausage",
    "jaboticaba",
    "jackfruit",
    "jaggery",
    "jalapeno_pepper",
    "jambalaya",
    "jambul",
    "jam",
    "jelly",
    "jelly_bean",
    "jelly_roll",
    "jerusalem_artichoke",
    "jewfish",
    "jicama",
    "jiaozi",
    "johnnycake",
    "jordan_almond",
    "joule",
    "julep",
    "juniper_berry",
    "junket",
    "kaiser_roll",
    "kaki",
    "kale",
    "kale_salad",
    "kamut",
    "kangaroo",
    "kasha",
    "kebab",
    "kedgeree",
    "kelp",
    "ketchup",
    "kettle_corn",
    "key_lime_pie",
    "khichdi",
    "kidney_bean",
    "kielbasa",
    "kimchi",
    "king_crab",
    "kingfish",
    "kipper",
    "kir",
    "kirsch",
    "kishke",
    "kiwi",
    "kohlrabi",
    "kombu",
    "kombucha",
    "korma",
    "kouign_amann",
    "kourabiedes",
    "kugel",
    "kumquat",
    "kung_pao_chicken",
    "kvass",
    "labneh",
    "ladyfinger",
    "lahmacun",
    "laksa",
    "lamb",
    "lamb_chop",
    "lamb_curry",
    "lamb_shank",
    "lamb_stew",
    "lamington",
    "langouste",
    "langoustine",
    "lapsang_souchong",
    "lard",
    "lasagna",
    "latke",
    "latte",
    "lava_cake",
    "lavender",
    "leafy_green_vegetable",
    "lebanese_seven_spices",
    "leche_flan",
    "lecsó",
    "leek",
    "leek_and_potato_soup",
    "legume",
    "lemon",
    "lemon_and_herb_chicken",
    "lemon_bar",
    "lemon_chicken",
    "lemon_curd",
    "lemon_meringue_pie",
    "lemon_pepper",
    "lemon_scone",
    "lemon_sorbet",
    "lemon_tart",
    "lemonade",
    "lemongrass",
    "lentil",
    "lentil_soup",
    "lettuce",
    "lettuce_wrap",
    "li",
    "licorice",
    "light_cream",
    "lima_bean",
    "lime",
    "limeade",
    "limoncello",
    "lingcod",
    "lingonberry",
    "linguine",
    "linguini_with_clam_sauce",
    "liqueur",
    "litchi",
    "liver",
    "liver_and_onions",
    "liver_pate",
    "lobster",
    "lobster_bisque",
    "lobster_newberg",
    "lobster_roll",
    "lobster_thermidor",
    "loganberry",
    "lohan_chai",
    "loin",
    "lollipop",
    "longan",
    "longaniza",
    "loquat",
    "lorraine_quiche",
    "lotus_root",
    "lox",
    "lucuma",
    "lumaconi",
    "lumpia",
    "lunch_meat",
    "lychee",
    "lyonnaise_potatoes",
    "macadamia_nut",
    "macaroni",
    "macaroni_and_cheese",
    "macaroni_salad",
    "macaroon",
    "macaron",
    "mackerel",
    "madeira_cake",
    "madeleine",
    "mahi_mahi",
    "maize",
    "malabar_spinach",
    "malay_apple",
    "malfatti",
    "malt",
    "mamey_sapote",
    "mamey_zapot",
    "mammee",
    "manapua",
    "manchego",
    "mandarin_orange",
    "mandazi",
    "mango",
    "mango_lassi",
    "mango_pudding",
    "mango_salad",
    "mango_sticky_rice",
    "mangosteen",
    "manhattan",
    "manicotti",
    "manioc",
    "mansaf",
    "manti",
    "maple_syrup",
    "maracuja",
    "maraschino_cherry",
    "margarine",
    "margarita",
    "margherita_pizza",
    "marinade",
    "mariniere",
    "marionberry",
    "marjoram",
    "marmalade",
    "marmite",
    "marron_glace",
    "marrow",
    "marshmallow",
    "marsipan",
    "martini",
    "marzipan",
    "masala",
    "masala_dosa",
    "mascarpone",
    "mashed_potato",
    "mashed_sweet_potato",
    "matbucha",
    "matcha",
    "matzo",
    "matzo_ball",
    "matzo_ball_soup",
    "mayonnaise",
    "maytag_blue_cheese",
    "mazurek",
    "mead",
    "meat",
    "meat_pie",
    "meatball",
    "meatball_sub",
    "meatloaf",
    "medjool_date",
    "medlar",
    "medu_vada",
    "melba_toast",
    "melon",
    "menudo",
    "meringue",
    "mesclun",
    "mesquite",
    "meuniere",
    "mexican_rice",
    "mexican_street_corn",
    "meyer_lemon",
    "meze",
    "milk",
    "milk_chocolate",
    "milkshake",
    "millet",
    "mille_feuille",
    "mincemeat_pie",
    "minestrone",
    "mint",
    "mint_julep",
    "mint_sauce",
    "minute_steak",
    "mirabelle",
    "mirin",
    "miso",
    "miso_soup",
    "missouri",
    "mixed_berry_pie",
    "mixed_fruit",
    "mixed_greens",
    "mixed_grill",
    "mixed_nuts",
    "mixed_seafood",
    "mixed_vegetables",
    "mochi",
    "mochi_ice_cream",
    "mock_apple_pie",
    "mock_turtle_soup",
    "modjeska",
    "mofongo",
    "mojito",
    "molasses",
    "mole",
    "mole_poblano",
    "monkfish",
    "monkey_bread",
    "monster_cookie",
    "montana",
    "monte_cristo_sandwich",
    "montmorency_cherry",
    "moo_goo_gai_pan",
    "moqueca",
    "morel",
    "moroccan_spices",
    "mortadella",
    "mostaccioli",
    "moussaka",
    "mousse",
    "mozzarella",
    "mozzarella_stick",
    "muesli",
    "muffin",
    "muhammara",
    "mujadara",
    "mulberry",
    "mulled_wine",
    "mulligatawny_soup",
    "mung_bean",
    "mushroom",
    "mushroom_risotto",
    "mushroom_soup",
    "mussel",
    "mustard",
    "mustard_greens",
    "mutton",
    "naan",
    "nacho",
    "nagaimo",
    "nance",
    "nashi_pear",
    "nasi_goreng",
    "nasi_lemak",
    "nasturtium",
    "navarin",
    "navel_orange",
    "neapolitan_ice_cream",
    "nebrodi_mountains",
    "nectarine",
    "neeps_and_tatties",
    "nes-yogurt_parfait",
    "nesselrode_pie",
    "nettle",
    "new_england_clam_chowder",
    "new_york_cheesecake",
    "new_york_strip_steak",
    "newburg",
    "nigella_seed",
    "nigiri",
    "nishiki_rice",
    "noodle",
    "noodle_soup",
    "nori",
    "normandy_tart",
    "nougat",
    "nut",
    "nut_butter",
    "nutmeg",
    "oat",
    "oat_cake",
    "oatmeal",
    "oatmeal_cookie",
    "oatmeal_raisin_cookie",
    "octopus",
    "oeufs_a_la_neige",
    "oeufs_en_meurette",
    "oxtail",
    "oxtail_soup",
    "oyster",
    "oyster_sauce",
    "oyster_stuffing",
    "paella",
    "page_markup_language",
    "pakora",
    "paneer",
    "paneer_tikka",
    "paneer_tikka_masala",
    "panettone",
    "panna_cotta",
    "panini",
    "panzanella",
    "papaya",
    "pappardelle",
    "paprika",
    "parfait",
    "parmigiana",
    "parmigiano_reggiano",
    "parsley",
    "parsnip",
    "partridge",
    "passion_fruit",
    "pasta",
    "pasta_salad",
    "pasteis_de_nata",
    "pasteles",
    "pastie",
    "pastitsio",
    "pastrami",
    "pastry",
    "pate",
    "pate_chaud",
    "pave",
    "pavlova",
    "pea",
    "pea_and_ham_soup",
    "pea_soup",
    "peach",
    "peach_cobbler",
    "peach_melba",
    "peach_pie",
    "peanut",
    "peanut_butter",
    "peanut_butter_and_jelly_sandwich",
    "peanut_butter_cookie",
    "peanut_sauce",
    "pear",
    "pear_salad",
    "pecan",
    "pecan_pie",
    "pecorino",
    "peking_duck",
    "penne",
    "penne_alla_vodka",
    "pepper",
    "pepper_steak",
    "peppermint",
    "pepperoni",
    "pepperoni_pizza",
    "perch",
    "periwinkle",
    "persimmon",
    "peruvian_spices",
    "pesto",
    "petit_four",
    "pheasant",
    "pho",
    "picadillo",
    "piccata",
    "piccalilli",
    "pickle",
    "pickled_cucumber",
    "pickled_ginger",
    "pickled_onion",
    "pickled_pepper",
    "pie",
    "pierogi",
    "pigeon",
    "pigeon_pea",
    "pig",
    "pignoli",
    "pilaf",
    "pimento",
    "pimento_cheese",
    "pina_colada",
    "pine_nut",
    "pineapple",
    "pineapple_and_ham_pizza",
    "pineapple_upside_down_cake",
    "pinot_noir",
    "pint",
    "pinto_bean",
    "pipian",
    "piquillo_pepper",
    "piri_piri_chicken",
    "pirozhki",
    "pistachio",
    "pistachio_ice_cream",
    "pistou",
    "pita",
    "pitaya",
    "pizza",
    "pizza_roll",
    "plantain",
    "plum",
    "plum_tomato",
    "poached_egg",
    "poblano_pepper",
    "poi",
    "poire_belle_helene",
    "poisson",
    "polenta",
    "polish_sausage",
    "pollock",
    "pomegranate",
    "pomelo",
    "pompano_en_papillote",
    "pop_tart",
    "popcorn",
    "popcorn_chicken",
    "popover",
    "poppy_seed",
    "poppy_seed_muffin",
    "porcini",
    "porgy",
    "pork",
    "pork_and_beans",
    "pork_belly",
    "pork_chop",
    "pork_pie",
    "pork_rind",
    "pork_roast",
    "pork_sate",
    "pork_schnitzel",
    "pork_stew",
    "pork_tenderloin",
    "pork_vindaloo",
    "port",
    "port_wine_cheese",
    "porter",
    "porterhouse_steak",
    "portobello_mushroom",
    "pot_de_creme",
    "pot_roast",
    "pot_sticker",
    "potato",
    "potato_bread",
    "potato_chip",
    "potato_gnocchi",
    "potato_pancake",
    "potato_salad",
    "potato_skin",
    "potato_soup",
    "potato_wedge",
    "pote",
    "potica",
    "potted_shrimp",
    "poutine",
    "pound_cake",
    "poussin",
    "praline",
    "prawn",
    "prawn_cocktail",
    "prawn_cracker",
    "preserve",
    "pretzel",
    "prickly_pear",
    "prime_rib",
    "profiterole",
    "prosciutto",
    "provolone",
    "prune",
    "pumpkin",
    "pumpkin_pie",
    "pumpkin_seed",
    "pumpernickel",
    "pupusa",
    "puree",
    "puttanesca",
    "quail",
    "quail_egg",
    "quatre_epices",
    "quatre_quarts",
    "queen_cake",
    "quesadilla",
    "queso",
    "queso_anejo",
    "queso_blanco",
    "queso_fresco",
    "quiche",
    "quince",
    "quinoa",
    "rabbit",
    "racines",
    "rack_of_lamb",
    "raclette",
    "radicchio",
    "radish",
    "ragout",
    "rainbow_trout",
    "raisin",
    "raisin_bread",
    "raita",
    "rambutan",
    "ramen",
    "ranch_dressing",
    "rapini",
    "raspberry",
    "raspberry_coulis",
    "raspberry_jam",
    "raspberry_sorbet",
    "raspberry_torte",
    "ratatouille",
    "ravioli",
    "ray",
    "razor_clam",
    "red_bean",
    "red_bean_paste",
    "red_cabbage",
    "red_curry",
    "red_delicious_apple",
    "red_lentil",
    "red_onion",
    "red_pepper",
    "red_potato",
    "red_snapper",
    "red_velvet_cake",
    "red_wine",
    "redfish",
    "refried_beans",
    "reuben_sandwich",
    "rhubarb",
    "rhubarb_pie",
    "rib_eye_steak",
    "rib",
    "ribollita",
    "rice",
    "rice_and_beans",
    "rice_ball",
    "rice_cake",
    "rice_noodle",
    "rice_paper",
    "rice_pudding",
    "rice_vermicelli",
    "ricotta",
    "ricotta_cheesecake",
    "rigatoni",
    "rillettes",
    "risotto",
    "roast_beef",
    "roast_beef_sandwich",
    "roast_chicken",
    "roast_duck",
    "roast_goose",
    "roast_lamb",
    "roast_pork",
    "roast_turkey",
    "roast_vegetables",
    "roasted_cauliflower",
    "roasted_chicken",
    "roasted_garlic",
    "roasted_potatoes",
    "roasted_red_pepper",
    "roasted_vegetables",
    "rosemary",
    "rock_cake",
    "rock_lobster",
    "rockfish",
    "rocky_road_ice_cream",
    "roe",
    "rogan_josh",
    "roll",
    "rolled_oat",
    "romaine_lettuce",
    "romanesco",
    "rooibos",
    "roquefort",
    "rose_apple",
    "rose_hip",
    "rose_water",
    "roti",
    "rotini",
    "rotisserie_chicken",
    "rougail_saucisse",
    "roulade",
    "round_steak",
    "roux",
    "royal_icing",
    "rub",
    "rum",
    "rum_ball",
    "rum_cake",
    "rumtopf",
    "runner_bean",
    "rusk",
    "russian_dressing",
    "rutabaga",
    "rye",
    "rye_bread",
    "s_more",
    "saba_goma",
    "saba_zushi",
    "sablefish",
    "sacchetti",
    "saffron",
    "sage",
    "sago",
    "sake",
    "salad",
    "salad_dressing",
    "salami",
    "salmon",
    "salmon_burger",
    "salmon_sushi",
    "salsa",
    "salsa_verde",
    "salsify",
    "salt",
    "salt_and_pepper_shrimp",
    "salt_cod",
    "saltimbocca",
    "samosa",
    "sancerre",
    "sandwich",
    "sangria",
    "sankthansaften",
    "santol",
    "sapodilla",
    "sapote",
    "sardine",
    "sashimi",
    "sassafras",
    "satay",
    "satsuma",
    "sauce",
    "sauerkraut",
    "sausage",
    "sausage_and_peppers",
    "sausage_gravy",
    "sausage_roll",
    "sauteed_mushrooms",
    "sauteed_spinach",
    "savarin",
    "savory",
    "savoy_cabbage",
    "scallion",
    "scallop",
    "scampi",
    "schnitzel",
    "scone",
    "scorzonera",
    "scrambled_eggs",
    "scrapple",
    "sea_bass",
    "sea_biscuit",
    "sea_bream",
    "sea_cucumber",
    "sea_lettuce",
    "sea_salt",
    "sea_trout",
    "sea_urchin",
    "seafood",
    "seafood_boil",
    "seafood_gumbo",
    "seafood_salad",
    "seared_tuna",
    "seaweed",
    "seaweed_salad",
    "seed",
    "semifreddo",
    "semolina",
    "semolina_pudding",
    "senda-bon_go",
    "sesame_ball",
    "sesame_chicken",
    "sesame_oil",
    "sesame_seed",
    "seswaa",
    "seven_layer_salad",
    "seviche",
    "sgabei",
    "shad",
    "shallot",
    "shashlik",
    "shaved_ice",
    "shawarma",
    "she_crab_soup",
    "sheeps_cheese",
    "shellfish",
    "shepherds_pie",
    "sherbet",
    "shiitake_mushroom",
    "shioyaki",
    "shirred_egg",
    "shiso",
    "shish_kebab",
    "shish_taouk",
    "shishito_pepper",
    "short_ribs",
    "shortbread",
    "shortcake",
    "shoyu_ramen",
    "shredded_beef",
    "shredded_chicken",
    "shredded_pork",
    "shrimp",
    "shrimp_and_grits",
    "shrimp_cocktail",
    "shrimp_scampi",
    "shrimp_toast",
    "sichuan_hot_pot",
    "sichuan_peppercorn",
    "side_dish",
    "silken_tofu",
    "simit",
    "singapore_chilli_crab",
    "sirloin_steak",
    "siumai",
    "skewer",
    "skirt_steak",
    "skordalia",
    "sloppy_joe",
    "slump",
    "smoked_eel",
    "smoked_salmon",
    "smoked_sausage",
    "smoked_trout",
    "smoot",
    "snack_food",
    "snail",
    "snake",
    "snapper",
    "snickerdoodle",
    "snow_crab",
    "snow_pea",
    "soda_bread",
    "sofrito",
    "soft_shell_crab",
    "soft_taco",
    "solyanka",
    "som_tam",
    "sonth",
    "sooji",
    "sop",
    "sorbet",
    "sorghum",
    "sorrel",
    "souffle",
    "sourdough_bread",
    "sour_cream",
    "soursop",
    "souse",
    "souvlaki",
    "sow",
    "soy_milk",
    "soy_sauce",
    "soymilk",
    "spaghetti",
    "spaghetti_and_meatballs",
    "spaghetti_bolognese",
    "spaghetti_carbonara",
    "spaghetti_puttanesca",
    "spaghetti_squash",
    "spaghetti_with_clam_sauce",
    "spanakopita",
    "spanish_rice",
    "spareribs",
    "spatchcock_chicken",
    "spearmint",
    "spelt",
    "spice",
    "spice_cake",
    "spices",
    "spicy_tuna_roll",
    "spinach",
    "spinach_and_artichoke_dip",
    "spinach_dip",
    "spinach_salad",
    "split_pea_soup",
    "sponge_cake",
    "spring_onion",
    "spring_roll",
    "sprinkle",
    "spumoni",
    "squab",
    "squash",
    "squash_blossom",
    "squid",
    "sriracha",
    "ssamjang",
    "stargazy_pie",
    "star_anise",
    "star_fruit",
    "steak",
    "steak_and_kidney_pie",
    "steak_and_potatoes",
    "steak_au_poivre",
    "steak_frites",
    "steak_sandwich",
    "steak_tartare",
    "steamed_buns",
    "steamed_clam",
    "steamed_mussel",
    "steamed_rice",
    "steamed_vegetable",
    "steelhead_trout",
    "stew",
    "sticky_toffee_pudding",
    "stilton_cheese",
    "stir_fried_vegetables",
    "stir_fry",
    "stollen",
    "stone_crab",
    "stout",
    "stracciatella",
    "stracotto",
    "strascinati",
    "strawberry",
    "strawberry_cheesecake",
    "strawberry_ice_cream",
    "strawberry_jam",
    "strawberry_rhubarb_pie",
    "strawberry_shortcake",
    "strawberry_sundae",
    "streusel",
    "string_bean",
    "string_cheese",
    "stroganoff",
    "stromboli",
    "strudel",
    "strychnine",
    "stuffed_cabbage",
    "stuffed_grape_leaves",
    "stuffed_mushrooms",
    "stuffed_peppers",
    "stuffing",
    "sub",
    "submarine_sandwich",
    "succotash",
    "suet",
    "sugar",
    "sugar_apple",
    "sugar_cookie",
    "sugarcane",
    "suimono",
    "sukiyaki",
    "sultana",
    "summer_pudding",
    "summer_roll",
    "summer_squash",
    "summer_sausage",
    "sundae",
    "sunflower_seed",
    "sunomono",
    "surf_and_turf",
    "surimi",
    "surstromming",
    "sushi",
    "sushi_roll",
    "swede",
    "swedish_meatballs",
    "sweet_and_sour_chicken",
    "sweet_and_sour_pork",
    "sweet_potato",
    "sweet_potato_casserole",
    "sweet_potato_fries",
    "sweet_potato_pie",
    "sweet_tea",
    "sweetbread",
    "swiss_chard",
    "swiss_cheese",
    "swiss_roll",
    "swordfish",
    "syllabub",
    "syrup",
    "t_bone_steak",
    "tabbouleh",
    "table_tennis",
    "tabletop_game",
    "taco",
    "taco_salad",
    "taffy",
    "tagine",
    "tagliatelle",
    "tahini",
    "tamarillo",
    "tamarind",
    "tamale",
    "tamale_pie",
    "tandori_chicken",
    "tandoori_chicken",
    "tangerine",
    "tapenade",
    "tapioca_pudding",
    "tara_root",
    "tarama_salad",
    "taramasalata",
    "taro",
    "tarragon",
    "tart",
    "tartar_sauce",
    "tarte_tatin",
    "tasso_ham",
    "tataki",
    "tater_tots",
    "tea",
    "tea_sandwich",
    "tempura",
    "tench",
    "teriyaki",
    "teriyaki_chicken",
    "terrine",
    "tex_mex",
    "thai_basil",
    "thai_curry",
    "thai_iced_tea",
    "thai_tea",
    "thousand_island_dressing",
    "thousand_year_egg",
    "thyme",
    "ti",
    "tian",
    "tiki_masala",
    "tilapia",
    "timbale",
    "tiramisu",
    "toad_in_the_hole",
    "toast",
    "toasted_ravioli",
    "toffee",
    "tofu",
    "tofu_scramble",
    "tomatillo",
    "tomato",
    "tomato_and_basil_soup",
    "tomato_juice",
    "tomato_ketchup",
    "tomato_salad",
    "tomato_sauce",
    "tomato_soup",
    "tongsui",
    "tongue",
    "tonic_water",
    "tonkatsu",
    "tonno_fagioli",
    "torte",
    "tortellini",
    "tortiere",
    "tortilla",
    "tortilla_chip",
    "tortilla_soup",
    "tournedos_rossini",
    "tourtiere",
    "tower",
    "trail_mix",
    "tramezzino",
    "trifle",
    "triticale",
    "trout",
    "truffle",
    "tuna",
    "tuna_casserole",
    "tuna_melt",
    "tuna_salad",
    "tuna_salad_sandwich",
    "tuna_sashimi",
    "tuna_steak",
    "tuna_tartare",
    "turban",
    "turbot",
    "turducken",
    "turkey",
    "turkey_burger",
    "turkey_club",
    "turkey_meatball",
    "turkey_sausage",
    "turmeric",
    "turnip",
    "turnip_greens",
    "turnover",
    "turtle",
    "turtle_bean_soup",
    "tutti_frutti",
    "twice_baked_potato",
    "tzatziki",
    "ube",
    "ugli_fruit",
    "udon",
    "unagi",
    "upside_down_cake",
    "urchin",
    "vanilla",
    "vanilla_bean",
    "vanilla_ice_cream",
    "vanilla_pudding",
    "vasilopita",
    "veal",
    "veal_chop",
    "veal_milanese",
    "veal_parmigiana",
    "veal_piccata",
    "veal_scallopini",
    "vegetable",
    "vegetable_biryani",
    "vegetable_curry",
    "vegetable_lasagna",
    "vegetable_oil",
    "vegetable_samosa",
    "vegetable_soup",
    "vegetable_stew",
    "vegetable_stir_fry",
    "vegetarian_chili",
    "vegetarian_pizza",
    "veggie_burger",
    "veloute_sauce",
    "venison",
    "vermicelli",
    "vermouth",
    "vichyssoise",
    "victoria_sponge",
    "vidalia_onion",
    "vindaloo",
    "vinegar",
    "violet",
    "vitello_tonnato",
    "vodka",
    "vol_au_vent",
    "waffle",
    "wakame",
    "waldorf_salad",
    "walnut",
    "wasabi",
    "water_biscuit",
    "water_chestnut",
    "watercress",
    "watercress_soup",
    "watermelon",
    "wedding_cake",
    "welsh_rarebit",
    "wendy_s",
    "western_omelette",
    "wheat",
    "wheat_bread",
    "wheatgrass",
    "whelk",
    "whey",
    "whipped_cream",
    "whiskey",
    "whiskey_sour",
    "white_bean",
    "white_cabbage",
    "white_chocolate",
    "white_currant",
    "white_fish",
    "white_peach",
    "white_pepper",
    "white_radish",
    "white_rice",
    "white_wine",
    "whitebait",
    "whiting",
    "whole_wheat_bread",
    "wild_boar",
    "wild_rice",
    "wild_strawberry",
    "wild_thyme",
    "wildebeest",
    "willow",
    "wine",
    "wing",
    "winter_melon",
    "winter_squash",
    "wolfberry",
    "won_ton",
    "wonton_soup",
    "wood_apple",
    "woodcock",
    "woodruff",
    "worcestershire_sauce",
    "worm",
    "wrap",
    "xanthan_gum",
    "xenarthra",
    "xenopus",
    "xenotime",
    "xigua",
    "xiphias",
    "xmas_pudding",
    "yam",
    "yam_bean",
    "yardlong_bean",
    "yeast",
    "yellow_bell_pepper",
    "yellow_eyed_pea",
    "yellow_squash",
    "yellowtail",
    "yema",
    "yerba_mate",
    "yew",
    "yogurt",
    "yorkshire_pudding",
    "yule_log",
    "yuzu",
    "zander",
    "zanthoxylum",
    "zepola",
    "zeppole",
    "zigeunerschnitzel",
    "zinfandel",
    "zingara",
    "ziti",
    "zizania",
    "ziziphus",
    "zucchini",
    "zucchini_bread",
    "zuppa_inglese",
    "zwieback",
  ];
}
